#!/usr/bin/env bash

set -o errexit

command -v xrandr &> /dev/null || error "required program 'xrandr' not installed"

function error {
	echo ERROR: "$1"
	exit 1
}

function usage {
	echo "Usage: $(basename $0) [OPTION]"
	echo "Control internal and external display settings."
	echo ""
	echo "OPTIONS:"
	echo "  dpi         print dpi depending on current monitor."
	echo "  primary     toggle the primary monitor [on|off]."
	echo "  list        list currently connected displays."
	exit 0
}

function dpi {
	EXTERNAL=$(xrandr | grep -q "[0-9] connected [0-9]")
	if [ $? -ne 0 ]; then
		XDPI=144
	else
		XDPI=96
	fi
	echo ${XDPI}
}

function primary {
	PRIMARY=$(xrandr | grep "primary" | awk '{print $1}')
	if [ -z "${PRIMARY}" ]; then
		error "could not determine primary display"
	fi

	# check for an external display
	EXTERNAL=$(xrandr | grep "[0-9] connected [0-9]" | awk '{print $1}')

	# check if the primary display is off
	OFF=$(xrandr | grep -q "${PRIMARY} connected primary [0-9]")
	if [ $? -ne 0 ]; then
		if [ -z "${EXTERNAL}" ]; then
			xrandr --output ${PRIMARY} --auto --primary
		else
			xrandr --output ${PRIMARY} --auto --left-of ${EXTERNAL} --primary
		fi
	else
		# only turn off primary display if external is connected
		if [ ! -z "${EXTERNAL}" ]; then
			xrandr --output ${PRIMARY} --off
		fi
	fi
}

function list {
	for m in $(xrandr | grep -E "[0-9] connected (primary )?[0-9]" | awk '{print $1}'); do
		echo $m
	done
}

case "$1" in
	dpi)
		dpi
		;;
	primary)
		primary
		;;
	list)
		list
		;;
	*)
		usage
		;;
esac
