#!/usr/bin/env bash

set -eo pipefail

function usage {
	echo "$(basename "$0") 0.1.1"
	echo "Control headphone settings"
	echo ""
	echo "USAGE:"
	echo "    $(basename "$0") [OPTION] <device>"
	echo ""
	echo "OPTIONS:"
	echo "  connnect       start bluetooth service and connect headphones"
	echo "  disconnect     disconnect headphones and stop bluetooth service"
	echo "  toggle         toggle headphone connection based on bluetooth service"
	exit 1
}

DEVICE="$2"

function connect {
	# start bluetooth service
	sudo systemctl start bluetooth

	# power on the bluetooth controller
	bluetoothctl power on

	# get device id
	DEVICE=$(bluetoothctl paired-devices | head -n 1 | grep "$1" | awk '{print $2}')

	# connect to device
	bluetoothctl connect "${DEVICE}"
}

function disconnect {
	sudo systemctl stop bluetooth
}

function toggle {
	BLUETOOTH=$(systemctl show -p ActiveState --value bluetooth)
	if [[ "${BLUETOOTH}" == "inactive" ]]; then
		connect "$1"
	else
		disconnect
	fi
}

case "$1" in
	connect)
		connect "$2"
		;;
	disconnect)
		disconnect
		;;
	toggle)
		toggle "$2"
		;;
	*)
		usage
		;;
esac
