#!/usr/bin/env bash

function error {
	echo ERROR: "$1"
	exit 1
}

function usage {
	echo "Usage: $(basename $0) [OPTION]"
	echo "Control headphone settings."
	echo ""
	echo "OPTIONS"
	echo "  connnect       start bluetooth service and connect headphones."
	echo "  disconnect     disconnect headphones and stop bluetooth service."
	echo "  toggle         toggle headphone connection based on bluetooth service."
	exit 0
}

command -v bluetoothctl &> /dev/null || error "required program 'bluetoothctl' not installed"

function connect {
	BLUETOOTH=$(sudo systemctl start bluetooth)
	if [ $? -ne 0 ]; then
		error "failed to start bluetooth service"
	fi

	POWER=$(bluetoothctl power on)
	if [ $? -ne 0 ]; then
		error "failed to power on bluetooth"
	fi

	DEVICES=$(bluetoothctl paired-devices)
	if [ $? -ne 0 ]; then
		error "failed to get paired bluetooth devices"
	fi

	DEVICE=$(echo ${DEVICES} | head -n 1 | awk '{print $2}')

	CONNECT=$(bluetoothctl connect ${DEVICE})
	if [ $? -ne 0 ]; then
		error "failed to connect to bluetooth device: ${DEVICE}"
	fi
}

function disconnect {
	BLUETOOTH=$(sudo systemctl stop bluetooth)
	if [ $? -ne 0 ]; then
		error "failed to stop bluetooth service"
	fi
}

function toggle {
	BLUETOOTH=$(systemctl is-active bluetooth)
	if [ $? -ne 0 ]; then
		connect
	else
		disconnect
	fi
}

case "$1" in
	connect)
		connect
		;;
	disconnect)
		disconnect
		;;
	toggle)
		toggle
		;;
	*)
		usage
		;;
esac
