#!/usr/bin/env bash

set -e

function usage {
	echo "$(basename "$0") 0.1.0"
	echo "Control battery charge threshold settings"
	echo ""
	echo "USAGE:"
	echo "    $(basename "$0") [OPTION]"
	echo ""
	echo "OPTIONS:"
	echo "  threshold    set the battery charge stop/start thresholds"
	echo "  fullcharge   set the battery charge stop threshold to 100%"
	exit 1
}

function check_root {
	if [[ "$EUID" -ne 0 ]]; then
		echo "Error: must be ran as root"
		exit 1
	fi
}

function check_threshold {
	if ! [[ "$1" =~ ^[0-9]+$ ]] || [[ "$1" -lt 0 ]] || [[ "$1" -gt 100 ]]; then
		echo "Error: charge threshold must be between 0-100"
		exit 1
	fi
}

function threshold {
	check_threshold "$1"
	check_threshold "$2"

	if [[ "$2" -lt "$1" ]]; then
		echo "Error: stop threshold must be greater than start threshold"
		exit 1
	fi

	echo "$1" > /sys/class/power_supply/BAT0/charge_start_threshold
	echo "$1" > /sys/class/power_supply/BAT0/charge_control_start_threshold
	echo "$2" > /sys/class/power_supply/BAT0/charge_stop_threshold
	echo "$2" > /sys/class/power_supply/BAT0/charge_control_end_threshold

	echo "Battery will start charging below $1% and stop charing at $2%"
}

function fullcharge {
	threshold 96 100
}

case "$1" in
	threshold)
		check_root
		threshold "$2" "$3"
		;;
	fullcharge)
		check_root
		fullcharge
		;;
	*)
		usage
		;;
esac
