#!/usr/bin/env bash

set -e

# get the primary display
PRIMARY=$(xrandr | grep "^eDP-[0-9] connected" | awk '{print $1}')
if [ -z "${PRIMARY}" ]; then
	echo "error: could not determine primary display"
	exit 1
fi

# check for external HDMI or DP displays and return first entry
EXTERNAL=$(xrandr | grep -E "^(DP|HDMI)-[0-9] connected" | head -n1 | awk '{print $1}')

function usage {
	echo "$(basename "$0") 0.1.0"
	echo "Control internal and external display output"
	echo ""
	echo "USAGE:"
	echo "    $(basename "$0") [OPTION]"
	echo ""
	echo "OPTIONS:"
	echo "    dual       turn both primary and extarnal displays on"
	echo "    primary    turn on primary display only"
	echo "    external   turn on external display only"
	exit 1
}

function dual {
	# if no external display, fail
	if [ -z "${EXTERNAL}" ]; then
		echo "error: could not determine external display"
		exit 1
	fi

	xrandr --output "${PRIMARY}" --auto --left-of "${EXTERNAL}" --output "${EXTERNAL}" --auto --primary
	i3-msg restart
}

function primary {
	# if no external display, set primary only
	if [ -z "${EXTERNAL}" ]; then
		xrandr --output "${PRIMARY}" --auto --primary
	else
		xrandr --output "${PRIMARY}" --auto --primary --output "${EXTERNAL}" --auto --off
	fi

	i3-msg restart
}

function external {
	# if no external display, fail
	if [ -z "${EXTERNAL}" ]; then
		echo "error: could not determine external display"
		exit 1
	fi

	xrandr --output "${PRIMARY}" --off --output "${EXTERNAL}" --auto --primary
	i3-msg restart
}

case "$1" in
	dual)
		dual
		;;
	primary)
		primary
		;;
	external)
		external
		;;
	*)
		usage
		;;
esac
