#!/usr/bin/env bash

set -e

if [[ -z $1 ]]; then
	echo "missing block device, try: $(basename "$0") <DEVICE> [-u]"
	exit 1
fi

DEV=$1
UMNT=$2
PART=${DEV##*/}

if [[ ${UMNT} == "-u" ]]; then
	umount /dev/mapper/"${PART}"
	cryptsetup luksClose "${PART}"
	exit 0
fi

cryptsetup luksOpen "${DEV}" "${PART}"
mount /dev/mapper/"${PART}" /mnt
