#!/usr/bin/env bash

set -eo pipefail

function usage {
	echo "$(basename "$0") 0.2.0"
	echo "Control bluetooth headphone settings."
	echo ""
	echo "USAGE:"
	echo "    $(basename "$0") [OPTION] <device>"
	echo ""
	echo "OPTIONS:"
	echo "  connnect       start bluetooth service and connect headphones"
	echo "  disconnect     disconnect headphones and stop bluetooth service"
	echo "  toggle         toggle headphone connection based on bluetooth service"
	exit 1
}

function connect {
	# Power on the bluetooth controller.
	bluetoothctl power on

	# Get device id.
	DEVICE=$(bluetoothctl devices Paired | head -n 1 | grep "$1" | awk '{print $2}')

	# Connect to device.
	bluetoothctl connect "${DEVICE}"
}

function disconnect {
	# Power off the bluetooth controller.
	bluetoothctl power off
}

function toggle {
	# Get device id.
	DEVICE=$(bluetoothctl devices Paired | head -n 1 | grep "$1" | awk '{print $2}')

	# Check if current device is already connected.
	CONNECTED=$(bluetoothctl info "${DEVICE}" | grep "Connected:" | awk '{print $2}')
	if [[ "${CONNECTED}" == "no" ]]; then
		connect "$1"
	else
		disconnect
	fi
}

case "$1" in
	connect)
		connect "$2"
		;;
	disconnect)
		disconnect
		;;
	toggle)
		toggle "$2"
		;;
	*)
		usage
		;;
esac
