#!/usr/bin/env bash

set -eo pipefail

function usage {
	echo "$(basename "$0") 0.3.0"
	echo "Control WireGuard profiles"
	echo ""
	echo "USAGE:"
	echo "    $(basename "$0") [OPTION] <CONFIG>"
	echo ""
	echo "OPTIONS:"
	echo "  up <CONFIG>      start the WireGuard client with a given config"
	echo "  down             stop the WireGuard client"
	echo "  list             list all WireGuard client configs"
	exit 1
}

function wg_up {
	if [[ -z "$1" ]]; then
		usage
	fi

	# Copy the desired config to wg0 so we can reference a single interface: ip link
	sudo cp /etc/wireguard/"$1".conf /etc/wireguard/wg0.conf

	# Connect to the server.
	sudo wg-quick up wg0
}

function list {
	local profiles=$(sudo find /etc/wireguard/ -name "*.conf" -type f -printf '%P\n' | sed 's/\.[^.]*$//')

	if [[ -z "$profiles" ]]; then
		echo "No profiles installed."
		exit 0
	fi

	for prof in $profiles
	do
		if ip link | grep -q "$prof"
		then
			prof="$prof (active)"
		fi
		echo "$prof"
	done
}

case "$1" in
	up)
		wg_up "$2"
		;;
	down)
		sudo wg-quick down wg0
		;;
	list)
		list
		;;
	*)
		usage
		;;
esac
