#!/usr/bin/env bash

set -eo pipefail

function usage {
	echo "$(basename "$0") 0.2.0"
	echo "Control WireGuard profiles"
	echo ""
	echo "USAGE:"
	echo "    $(basename "$0") [OPTION] <CONFIG>"
	echo ""
	echo "OPTIONS:"
	echo "  up <CONFIG>      start the WireGuard client with a given config"
	echo "  down <CONFIG>    stop the WireGuard client for a given config"
	echo "  list             list all WireGuard client configs"
	exit 1
}

function wg_client {
	if [[ -z "$2" ]]; then
		usage
	fi
	sudo wg-quick "$1" "$2"
}

function list {
	for prof in $(sudo find /etc/wireguard/ -name "*.conf" -type f -printf '%P\n' | sed 's/\.[^.]*$//')
	do
		if ip link | grep -q "$prof"
		then
			prof="$prof (active)"
		fi
		echo "$prof"
	done
}

case "$1" in
	up)
		wg_client "up" "$2"
		;;
	down)
		wg_client "down" "$2"
		;;
	list)
		list
		;;
	*)
		usage
		;;
esac
